apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: web
    name: web
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: web
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: web2
    name: web2
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: web2
    type: ClusterIP
kind: List
